config/routes.rb
Rails.application.routes.draw do
  resources :forma_pagamentos
  devise_for :users
  resources :entrega_estampas
  resources :estampas
  resources :caixas
  resources :despesas
  resources :vendas
  resources :entregas
  resources :costuras
  resources :corte_modelos
  resources :cortes
  resources :modelos
  resources :debitos
  resources :pag_parcelas
  resources :compras
  resources :fornecedors
  root to: "caixas#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/caixa.rb
class Caixa < ApplicationRecord
  belongs_to :compra
  belongs_to :despesa
  belongs_to :venda
  belongs_to :costura
  belongs_to :corte
  belongs_to :estampa
end

app/models/compra.rb
class Compra < ApplicationRecord
  belongs_to :fornecedor
end

app/models/corte.rb
class Corte < ApplicationRecord
  belongs_to :compra
  has_many :corte_modelos
  has_many :modelos

  accepts_nested_attributes_for :compra, :corte_modelos, :modelos, reject_if: :all_blank, allow_destroy: true


end

app/models/corte_modelo.rb
class CorteModelo < ApplicationRecord
  belongs_to :modelo
  belongs_to :corte
end

app/models/costura.rb
class Costura < ApplicationRecord
  belongs_to :corte
end

app/models/debito.rb
class Debito < ApplicationRecord
  belongs_to :compra
end

app/models/despesa.rb
class Despesa < ApplicationRecord
end

app/models/entrega.rb
class Entrega < ApplicationRecord
  belongs_to :costura
end

app/models/entrega_estampa.rb
class EntregaEstampa < ApplicationRecord
  belongs_to :estampa
  belongs_to :costura
end

app/models/estampa.rb
class Estampa < ApplicationRecord
  belongs_to :corte
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/models/modelo.rb
class Modelo < ApplicationRecord
	has_many :cortes
	has_many :estampas
	has_many_attached :fotos
end

app/models/pag_parcela.rb
class PagParcela < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venda.rb
class Venda < ApplicationRecord
end

app/controllers/pag_parcelas_controller.rb
class PagParcelasController < ApplicationController
  before_action :set_pag_parcela, only: [:show, :edit, :update, :destroy]

  # GET /pag_parcelas
  # GET /pag_parcelas.json
  def index
    @pag_parcelas = PagParcela.all
  end

  # GET /pag_parcelas/1
  # GET /pag_parcelas/1.json
  def show
  end

  # GET /pag_parcelas/new
  def new
    @pag_parcela = PagParcela.new
  end

  # GET /pag_parcelas/1/edit
  def edit
  end

  # POST /pag_parcelas
  # POST /pag_parcelas.json
  def create
    @pag_parcela = PagParcela.new(pag_parcela_params)

    respond_to do |format|
      if @pag_parcela.save
        format.html { redirect_to @pag_parcela, notice: 'Pag parcela was successfully created.' }
        format.json { render :show, status: :created, location: @pag_parcela }
      else
        format.html { render :new }
        format.json { render json: @pag_parcela.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pag_parcelas/1
  # PATCH/PUT /pag_parcelas/1.json
  def update
    respond_to do |format|
      if @pag_parcela.update(pag_parcela_params)
        format.html { redirect_to @pag_parcela, notice: 'Pag parcela was successfully updated.' }
        format.json { render :show, status: :ok, location: @pag_parcela }
      else
        format.html { render :edit }
        format.json { render json: @pag_parcela.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pag_parcelas/1
  # DELETE /pag_parcelas/1.json
  def destroy
    @pag_parcela.destroy
    respond_to do |format|
      format.html { redirect_to pag_parcelas_url, notice: 'Pag parcela was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pag_parcela
      @pag_parcela = PagParcela.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pag_parcela_params
      params.require(:pag_parcela).permit(:data, :valorp, :pago)
    end
end

app/helpers/caixas_helper.rb
module CaixasHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/cortes_helper.rb
module CortesHelper
	def corte_qtd_total
    	if self.corte.blank?
      			0
    	else
      	   self.corte.qtd_total
    	end
    end

    def corte_compra_valor
    	if self.corte.blank?
      			0
    	else
      	   self.corte.compra.valor
    	end
    end
end

app/helpers/debitos_helper.rb
module DebitosHelper
end

app/helpers/modelos_helper.rb
module ModelosHelper
end

app/helpers/pag_parcelas_helper.rb
module PagParcelasHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/pag_parcelas/_form.html.erb
<%= form_with(model: pag_parcela, local: true) do |form| %>
  <% if pag_parcela.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pag_parcela.errors.count, "error") %> prohibited this pag_parcela from being saved:</h2>

      <ul>
      <% pag_parcela.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :pago %>
    <%= form.check_box :pago %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pag_parcelas/edit.html.erb
<h1>Editing Pag Parcela</h1>

<%= render 'form', pag_parcela: @pag_parcela %>

<%= link_to 'Show', @pag_parcela %> |
<%= link_to 'Back', pag_parcelas_path %>

app/views/pag_parcelas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pag Parcelas</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Pago</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pag_parcelas.each do |pag_parcela| %>
      <tr>
        <td><%= pag_parcela.data.strftime("%d/%m/%Y") %></td>
        <td><%= pag_parcela.pago %></td>
        <td><%= link_to 'Mostrar', pag_parcela %></td>
        <td><%= link_to 'Editar', edit_pag_parcela_path(pag_parcela) %></td>
        <td><%= link_to 'Deletar', pag_parcela, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Pag Parcela', new_pag_parcela_path %>

app/views/pag_parcelas/new.html.erb
<h1>New Pag Parcela</h1>

<%= render 'form', pag_parcela: @pag_parcela %>

<%= link_to 'Back', pag_parcelas_path %>

app/views/pag_parcelas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @pag_parcela.data.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Pago:</strong>
  <%= @pag_parcela.pago %>
</p>

<%= link_to 'Editar', edit_pag_parcela_path(@pag_parcela) %> |
<%= link_to 'Voltar', pag_parcelas_path %>