config/routes.rb
Rails.application.routes.draw do
  resources :forma_pagamentos
  devise_for :users
  resources :entrega_estampas
  resources :estampas
  resources :caixas
  resources :despesas
  resources :vendas
  resources :entregas
  resources :costuras
  resources :corte_modelos
  resources :cortes
  resources :modelos
  resources :debitos
  resources :pag_parcelas
  resources :compras
  resources :fornecedors
  root to: "caixas#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/caixa.rb
class Caixa < ApplicationRecord
  belongs_to :compra
  belongs_to :despesa
  belongs_to :venda
  belongs_to :costura
  belongs_to :corte
  belongs_to :estampa
end

app/models/compra.rb
class Compra < ApplicationRecord
  belongs_to :fornecedor
end

app/models/corte.rb
class Corte < ApplicationRecord
  belongs_to :compra
  has_many :corte_modelos
  has_many :modelos

  accepts_nested_attributes_for :compra, :corte_modelos, :modelos, reject_if: :all_blank, allow_destroy: true


end

app/models/corte_modelo.rb
class CorteModelo < ApplicationRecord
  belongs_to :modelo
  belongs_to :corte
end

app/models/costura.rb
class Costura < ApplicationRecord
  belongs_to :corte
end

app/models/debito.rb
class Debito < ApplicationRecord
  belongs_to :compra
end

app/models/despesa.rb
class Despesa < ApplicationRecord
end

app/models/entrega.rb
class Entrega < ApplicationRecord
  belongs_to :costura
end

app/models/estampa.rb
class Estampa < ApplicationRecord
  belongs_to :corte
end

app/models/forma_pagamento.rb
class FormaPagamento < ApplicationRecord
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/models/modelo.rb
class Modelo < ApplicationRecord
	has_many :cortes
	has_many :estampas
	has_many_attached :fotos
end

app/models/pag_parcela.rb
class PagParcela < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venda.rb
class Venda < ApplicationRecord
end

app/controllers/forma_pagamentos_controller.rb
class FormaPagamentosController < ApplicationController
  before_action :set_forma_pagamento, only: [:show, :edit, :update, :destroy]

  # GET /forma_pagamentos
  # GET /forma_pagamentos.json
  def index
    @forma_pagamentos = FormaPagamento.all
  end

  # GET /forma_pagamentos/1
  # GET /forma_pagamentos/1.json
  def show
  end

  # GET /forma_pagamentos/new
  def new
    @forma_pagamento = FormaPagamento.new
  end

  # GET /forma_pagamentos/1/edit
  def edit
  end

  # POST /forma_pagamentos
  # POST /forma_pagamentos.json
  def create
    @forma_pagamento = FormaPagamento.new(forma_pagamento_params)

    respond_to do |format|
      if @forma_pagamento.save
        format.html { redirect_to @forma_pagamento, notice: 'Forma pagamento was successfully created.' }
        format.json { render :show, status: :created, location: @forma_pagamento }
      else
        format.html { render :new }
        format.json { render json: @forma_pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forma_pagamentos/1
  # PATCH/PUT /forma_pagamentos/1.json
  def update
    respond_to do |format|
      if @forma_pagamento.update(forma_pagamento_params)
        format.html { redirect_to @forma_pagamento, notice: 'Forma pagamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @forma_pagamento }
      else
        format.html { render :edit }
        format.json { render json: @forma_pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forma_pagamentos/1
  # DELETE /forma_pagamentos/1.json
  def destroy
    @forma_pagamento.destroy
    respond_to do |format|
      format.html { redirect_to forma_pagamentos_url, notice: 'Forma pagamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forma_pagamento
      @forma_pagamento = FormaPagamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forma_pagamento_params
      params.require(:forma_pagamento).permit(:tipo, :ativo)
    end
end

app/helpers/caixas_helper.rb
module CaixasHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/cortes_helper.rb
module CortesHelper
	def corte_qtd_total
    	if self.corte.blank?
      			0
    	else
      	   self.corte.qtd_total
    	end
    end

    def corte_compra_valor
    	if self.corte.blank?
      			0
    	else
      	   self.corte.compra.valor
    	end
    end
end

app/helpers/debitos_helper.rb
module DebitosHelper
end

app/helpers/forma_pagamentos_helper.rb
module FormaPagamentosHelper
end

app/helpers/modelos_helper.rb
module ModelosHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/forma_pagamentos/_form.html.erb
<%= form_with(model: forma_pagamento, local: true) do |form| %>
  <% if forma_pagamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forma_pagamento.errors.count, "error") %> prohibited this forma_pagamento from being saved:</h2>

      <ul>
      <% forma_pagamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :ativo %>
    <%= form.check_box :ativo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forma_pagamentos/edit.html.erb
<h1>Editing Forma Pagamento</h1>

<%= render 'form', forma_pagamento: @forma_pagamento %>

<%= link_to 'Show', @forma_pagamento %> |
<%= link_to 'Back', forma_pagamentos_path %>

app/views/forma_pagamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forma Pagamentos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Ativo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forma_pagamentos.each do |forma_pagamento| %>
      <tr>
        <td><%= forma_pagamento.tipo %></td>
        <td><%= forma_pagamento.ativo %></td>
        <td><%= link_to 'Show', forma_pagamento %></td>
        <td><%= link_to 'Edit', edit_forma_pagamento_path(forma_pagamento) %></td>
        <td><%= link_to 'Destroy', forma_pagamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forma Pagamento', new_forma_pagamento_path %>

app/views/forma_pagamentos/new.html.erb
<h1>New Forma Pagamento</h1>

<%= render 'form', forma_pagamento: @forma_pagamento %>

<%= link_to 'Back', forma_pagamentos_path %>

app/views/forma_pagamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @forma_pagamento.tipo %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @forma_pagamento.ativo %>
</p>

<%= link_to 'Edit', edit_forma_pagamento_path(@forma_pagamento) %> |
<%= link_to 'Back', forma_pagamentos_path %>