config/routes.rb
Rails.application.routes.draw do
  resources :forma_pagamentos
  devise_for :users
  resources :entrega_estampas
  resources :estampas
  resources :caixas
  resources :despesas
  resources :vendas
  resources :entregas
  resources :costuras
  resources :corte_modelos
  resources :cortes
  resources :modelos
  resources :debitos
  resources :pag_parcelas
  resources :compras
  resources :fornecedors
  root to: "caixas#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/caixa.rb
class Caixa < ApplicationRecord
  belongs_to :compra
  belongs_to :despesa
  belongs_to :venda
  belongs_to :costura
  belongs_to :corte
  belongs_to :estampa
end

app/models/compra.rb
class Compra < ApplicationRecord
  belongs_to :fornecedor
end

app/models/corte.rb
class Corte < ApplicationRecord
  belongs_to :compra
  has_many :corte_modelos
  has_many :modelos

  accepts_nested_attributes_for :compra, :corte_modelos, :modelos, reject_if: :all_blank, allow_destroy: true


end

app/models/corte_modelo.rb
class CorteModelo < ApplicationRecord
  belongs_to :modelo
  belongs_to :corte
end

app/models/costura.rb
class Costura < ApplicationRecord
  belongs_to :corte
end

app/models/debito.rb
class Debito < ApplicationRecord
  belongs_to :compra
end

app/models/despesa.rb
class Despesa < ApplicationRecord
end

app/models/entrega.rb
class Entrega < ApplicationRecord
  belongs_to :costura
end

app/models/entrega_estampa.rb
class EntregaEstampa < ApplicationRecord
  belongs_to :estampa
  belongs_to :costura
end

app/models/estampa.rb
class Estampa < ApplicationRecord
  belongs_to :corte
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/models/modelo.rb
class Modelo < ApplicationRecord
	has_many :cortes
	has_many :estampas
	has_many_attached :fotos
end

app/models/pag_parcela.rb
class PagParcela < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venda.rb
class Venda < ApplicationRecord
end

app/controllers/costuras_controller.rb
class CosturasController < ApplicationController
  before_action :set_costura, only: [:show, :edit, :update, :destroy]

  # GET /costuras
  # GET /costuras.json
  def index
    @costuras = Costura.all
  end

  # GET /costuras/1
  # GET /costuras/1.json
  def show
  end

  # GET /costuras/new
  def new
    @costura = Costura.new
  end

  # GET /costuras/1/edit
  def edit
  end

  # POST /costuras
  # POST /costuras.json
  def create
    @costura = Costura.new(costura_params)

    respond_to do |format|
      if @costura.save
        format.html { redirect_to @costura, notice: 'Costura was successfully created.' }
        format.json { render :show, status: :created, location: @costura }
      else
        format.html { render :new }
        format.json { render json: @costura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costuras/1
  # PATCH/PUT /costuras/1.json
  def update
    respond_to do |format|
      if @costura.update(costura_params)
        format.html { redirect_to @costura, notice: 'Costura was successfully updated.' }
        format.json { render :show, status: :ok, location: @costura }
      else
        format.html { render :edit }
        format.json { render json: @costura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costuras/1
  # DELETE /costuras/1.json
  def destroy
    @costura.destroy
    respond_to do |format|
      format.html { redirect_to costuras_url, notice: 'Costura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_costura
      @costura = Costura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def costura_params
      params.require(:costura).permit(:data, :faccao, :corte_id, :qtd_total)
    end
end

app/helpers/caixas_helper.rb
module CaixasHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/cortes_helper.rb
module CortesHelper
	def corte_qtd_total
    	if self.corte.blank?
      			0
    	else
      	   self.corte.qtd_total
    	end
    end

    def corte_compra_valor
    	if self.corte.blank?
      			0
    	else
      	   self.corte.compra.valor
    	end
    end
end

app/helpers/costuras_helper.rb
module CosturasHelper
end

app/helpers/debitos_helper.rb
module DebitosHelper
end

app/helpers/modelos_helper.rb
module ModelosHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/costuras/_form.html.erb
<%= form_with(model: costura, local: true) do |form| %>
  <% if costura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(costura.errors.count, "error") %> prohibited this costura from being saved:</h2>

      <ul>
      <% costura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :faccao %>
    <%= form.text_field :faccao %>
  </div>

  <div class="field">
    <%= form.label :corte_id %>
    <%= form.collection_select :corte_id, Corte.order(created_at: :desc), :id, :data, prompt: 'Selecione'  %>
  </div>

  <div class="field">
    <%= form.label :qtd_total %>
    <%= form.number_field :qtd_total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/costuras/edit.html.erb
<h1>Editing Costura</h1>

<%= render 'form', costura: @costura %>

<%= link_to 'Show', @costura %> |
<%= link_to 'Back', costuras_path %>

app/views/costuras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Costuras</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Faccao</th>
      <th>Corte</th>
      <th>Qtd total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costuras.each do |costura| %>
      <tr>
        <td><%= costura.data.strftime("%d/%m/%Y") %></td>
        <td><%= costura.faccao %></td>
        <td><%= costura.corte.data.strftime("%d/%m/%Y") %></td>
        <td><%= costura.qtd_total %></td>
        <td><%= link_to 'Mostrar', costura, :class => 'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to 'Editar', edit_costura_path(costura), :class => 'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to 'Deletar', costura, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-outline-primary btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Costura', new_costura_path, :class => 'btn btn-outline-primary btn-sm' %>

app/views/costuras/new.html.erb
<h1>New Costura</h1>

<%= render 'form', costura: @costura %>

<%= link_to 'Back', costuras_path %>

app/views/costuras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data envio:</strong>
  <%= @costura.data.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Faccao:</strong>
  <%= @costura.faccao %>
</p>

<p>
  <strong>Data do Corte:</strong>
  <%= @costura.corte.data.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Qtd total de Peças:</strong>
  <%= @costura.qtd_total %>
</p>

<%= link_to 'Editar', edit_costura_path(@costura), :class => 'btn btn-outline-primary btn-sm' %> |
<%= link_to 'Voltar', costuras_path, :class => 'btn btn-outline-primary btn-sm' %>