config/routes.rb
Rails.application.routes.draw do
  resources :forma_pagamentos
  devise_for :users
  resources :entrega_estampas
  resources :estampas
  resources :caixas
  resources :despesas
  resources :vendas
  resources :entregas
  resources :costuras
  resources :corte_modelos
  resources :cortes
  resources :modelos
  resources :debitos
  resources :pag_parcelas
  resources :compras
  resources :fornecedors
  root to: "caixas#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/caixa.rb
class Caixa < ApplicationRecord
  belongs_to :compra
  belongs_to :despesa
  belongs_to :venda
  belongs_to :costura
  belongs_to :corte
  belongs_to :estampa
end

app/models/compra.rb
class Compra < ApplicationRecord
  belongs_to :fornecedor
end

app/models/corte.rb
class Corte < ApplicationRecord
  belongs_to :compra
  has_many :corte_modelos
  has_many :modelos

  accepts_nested_attributes_for :compra, :corte_modelos, :modelos, reject_if: :all_blank, allow_destroy: true


end

app/models/corte_modelo.rb
class CorteModelo < ApplicationRecord
  belongs_to :modelo
  belongs_to :corte
end

app/models/costura.rb
class Costura < ApplicationRecord
  belongs_to :corte
end

app/models/debito.rb
class Debito < ApplicationRecord
  belongs_to :compra
end

app/models/despesa.rb
class Despesa < ApplicationRecord
end

app/models/entrega.rb
class Entrega < ApplicationRecord
  belongs_to :costura
end

app/models/entrega_estampa.rb
class EntregaEstampa < ApplicationRecord
  belongs_to :estampa
  belongs_to :costura
end

app/models/estampa.rb
class Estampa < ApplicationRecord
  belongs_to :corte
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/models/modelo.rb
class Modelo < ApplicationRecord
	has_many :cortes
	has_many :estampas
	has_many_attached :fotos
end

app/models/pag_parcela.rb
class PagParcela < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venda.rb
class Venda < ApplicationRecord
end

app/controllers/entrega_estampas_controller.rb
class EntregaEstampasController < ApplicationController
  before_action :set_entrega_estampa, only: [:show, :edit, :update, :destroy]

  # GET /entrega_estampas
  # GET /entrega_estampas.json
  def index
    @entrega_estampas = EntregaEstampa.all
  end

  # GET /entrega_estampas/1
  # GET /entrega_estampas/1.json
  def show
  end

  # GET /entrega_estampas/new
  def new
    @entrega_estampa = EntregaEstampa.new
  end

  # GET /entrega_estampas/1/edit
  def edit
  end

  # POST /entrega_estampas
  # POST /entrega_estampas.json
  def create
    @entrega_estampa = EntregaEstampa.new(entrega_estampa_params)

    respond_to do |format|
      if @entrega_estampa.save
        format.html { redirect_to @entrega_estampa, notice: 'Entrega estampa was successfully created.' }
        format.json { render :show, status: :created, location: @entrega_estampa }
      else
        format.html { render :new }
        format.json { render json: @entrega_estampa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entrega_estampas/1
  # PATCH/PUT /entrega_estampas/1.json
  def update
    respond_to do |format|
      if @entrega_estampa.update(entrega_estampa_params)
        format.html { redirect_to @entrega_estampa, notice: 'Entrega estampa was successfully updated.' }
        format.json { render :show, status: :ok, location: @entrega_estampa }
      else
        format.html { render :edit }
        format.json { render json: @entrega_estampa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrega_estampas/1
  # DELETE /entrega_estampas/1.json
  def destroy
    @entrega_estampa.destroy
    respond_to do |format|
      format.html { redirect_to entrega_estampas_url, notice: 'Entrega estampa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrega_estampa
      @entrega_estampa = EntregaEstampa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrega_estampa_params
      params.require(:entrega_estampa).permit(:data, :estampa_id, :valor, :costura_id, :obs, :perdas, :qtd_entregue)
    end
end

app/helpers/caixas_helper.rb
module CaixasHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/cortes_helper.rb
module CortesHelper
	def corte_qtd_total
    	if self.corte.blank?
      			0
    	else
      	   self.corte.qtd_total
    	end
    end

    def corte_compra_valor
    	if self.corte.blank?
      			0
    	else
      	   self.corte.compra.valor
    	end
    end
end

app/helpers/debitos_helper.rb
module DebitosHelper
end

app/helpers/entrega_estampas_helper.rb
module EntregaEstampasHelper
end

app/helpers/modelos_helper.rb
module ModelosHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/entrega_estampas/_form.html.erb
<%= form_with(model: entrega_estampa, local: true) do |form| %>
  <% if entrega_estampa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entrega_estampa.errors.count, "error") %> prohibited this entrega_estampa from being saved:</h2>

      <ul>
      <% entrega_estampa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :estampa_id, 'Data Entrega do Pacote' %>
    <%= form.collection_select :estampa_id, Estampa.order(created_at: :desc), :id, :data, prompt: 'Selecione' %>
  </div>

  <div class="field">
    <%= form.label :qtd_entregue %>
    <%= form.number_field :qtd_entregue %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="field">
    <%= form.label :costura_id %>
    <%= form.collection_select :costura_id, Costura.order(faccao: :desc), :id, :faccao, prompt: 'selecione' %>
  </div>

  <div class="field">
    <%= form.label :obs %>
    <%= form.text_area :obs %>
  </div>

  <div class="field">
    <%= form.label :perdas %>
    <%= form.number_field :perdas %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entrega_estampas/edit.html.erb
<h1>Editing Entrega Estampa</h1>

<%= render 'form', entrega_estampa: @entrega_estampa %>

<%= link_to 'Show', @entrega_estampa %> |
<%= link_to 'Back', entrega_estampas_path %>

app/views/entrega_estampas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entrega Estampas</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Estampa</th>
      <th>Qtd Rec</th>
      <th>Valor</th>
      <th>Costura</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entrega_estampas.each do |entrega_estampa| %>
      <tr>
        <td><%= entrega_estampa.data.strftime("%d/%m/%Y") %></td>
        <td><%= entrega_estampa.estampa.data.strftime("%d/%m/%Y") %></td>
        <td><%= entrega_estampa.qtd_entregue %></td>
        <td><%= valor_formatado(entrega_estampa.valor) %></td>
        <td><%= entrega_estampa.costura.faccao %></td>
        <td><%= link_to 'Mostrar', entrega_estampa, :class => 'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to 'Editar', edit_entrega_estampa_path(entrega_estampa), :class => 'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to 'Deletar', entrega_estampa, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-outline-primary btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Entrega de Estampa', new_entrega_estampa_path, :class => 'btn btn-outline-primary btn-sm' %>

app/views/entrega_estampas/new.html.erb
<h1>New Entrega Estampa</h1>

<%= render 'form', entrega_estampa: @entrega_estampa %>

<%= link_to 'Voltar', entrega_estampas_path %>

app/views/entrega_estampas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data Entrega:</strong>
  <%= @entrega_estampa.data.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Data da entrega do Pacote:</strong>
  <%= @entrega_estampa.estampa.data %>
</p>

<p>
<strong>Qtd Entregue:</strong>
  <%= @entrega_estampa.qtd_entregue %>
</p>

<p>
  <strong>Valor:</strong>
  <%= valor_formatado(@entrega_estampa.valor) %>
</p>

<p>
  <strong>Costura:</strong>
  <%= @entrega_estampa.costura.faccao %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @entrega_estampa.obs %>
</p>

<p>
  <strong>Perdas:</strong>
  <%= @entrega_estampa.perdas %>
</p>

<%= link_to 'Editar', edit_entrega_estampa_path(@entrega_estampa), :class => 'btn btn-outline-primary btn-sm' %> |
<%= link_to 'Voltar', entrega_estampas_path, :class => 'btn btn-outline-primary btn-sm' %>